### ISSUE TITLE
pulsein doesn't seem to work

### ISSUE THREAD

**Issue by nateGeorge** [rolandturner/yahi#1]
I've tried this and the pulseIn and it doesn't seem to work.  It's giving me particle counts in the 10s of thousands when it should be under 100 (measured by Dylos DC1700).  I think maybe it needs a capacitor for the power supply.

**Comment by rolandturner** [comment]
Intriguing. I've not calibrated against a local sensor yet, which size range were you using on the Dylos? (Yahi uses for its calibration source PM2.5 data produced by Singapore's NEA using both FRM and FEM, consequently I've not yet needed to compare with local instruments, although I do wish to.)

Power supply instability is certainly an area to look at: did you add a capacitor, did it help?

**Comment by nateGeorge** [comment]
I added 3 capacitors in parallel: 2200 uf, ~500 uf, and a 47uf, which was not enough to stabilize the power, even with the particle in manual mode and with the wifi disconnected.  For some reason it seems to occasionally draw power erratically.  At 2200uf and 5V, I think that's only supplying power for some hundredths of a second.  I think the photon and Shinyei need to be on dedicated power lines, or a boost converter might work, or a really large capacitor.  Rockvole shows a 2200uf cap in his design but I don't think it's enough.
https://github.com/Rockvole/indoor-air-quality-dashboard

**Comment by rolandturner** [comment]
I'm not in a position to claim viability of using the Photon, I've only tested with the Core.

If the Photon's power draw is spiky (e.g. if the means used to run the WiFi so much leaner is that large chunks of the radio are being turned on and off continually) then, sure, greater isolation will be required for the analogue electronics on the Shinyei. You could build an experiment to test this conclusively by powering the Shinyei from a battery (almost any "external USB charger" battery will do so long as you keep it delivering power, perhaps by putting a resistor across it) and connecting only the Photon's ground (required for reference) and the A0 pin (high impedance on the Photon side) to the Shinyei. If this causes the sensor to start yielding sensible data then, yes, you've isolated a power supply noise problem caused by the cleverness in the Photon. A separate battery isn't a long term solution in most cases (separate regulation with both parallel capacitance and serial inductance would presumably be necessary), but is enough to test the theory.

If the separate battery approach doesn't resolve the problem then there's almost certainly something else wrong.

**Comment by nateGeorge** [comment]
It seems to be a PSU issue, see this: https://community.particle.io/t/breadboard-indoor-air-quality-monitor/9138/32

I'm using super-cheap USB PSUs and hacked up usb cables, I think that's the issue.  Hopefully your PSU you use is good enough.

**Comment by rolandturner** [comment]
I do use seriously over-rated supplies, yes, but note also that I've only used the Core so far, not the Photon. My results may vary when I try a Photon...

**Comment by nateGeorge** [comment]
Nah I think you'll be fine, especially powering from the VIN.  I'm pretty
sure my problem was actually the USB cable, the wires inside are really
thin.  I'm not sure which guage but smaller than 22.
